---
- hosts: all
  become: yes
  tasks:
  - run: docker build --tag my-image:v1 .
  - name: Push to ECR
    id: ecr
    uses: jwalton/gh-ecr-push@v1
    with:
      access-key-id: AKIAQWUKFH6EWR43XC6A
      secret-access-key: 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
      region: ap-south-1
      image: my-image:v1
