---
- hosts: all
  become: yes
  tasks:
  - run: sudo docker image build --tag my-image:v1 .
  - name: Push to ECR
    id: ecr
    uses: jwalton/gh-ecr-push@v1
    with:
      access-key-id: AKIAQWUKFH6EWR43XC6A
      secret-access-key: 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
      region: ap-south-1
      image: my-image:v1
      repo: docker/repo
      tags: 1905201
      reate_repo: true
      set_repo_policy: true
      repo_policy_file: repo-policy.json
